[IMP] account move get journal sequence in name
acsone/account-financial-tools pull request #6
Opened 2017-12-18 14:26 UTC by mpanarin

An improvement, mentioned in https://github.com/OCA/account-financial-tools/pull/441#pullrequestreview-79155830 by @gurneyalex

2017-12-18 15:58 UTC, gurneyalex requested changes

2017-12-18 15:58 UTC, gurneyalex commented on account_asset_management/models/account_asset_line.py
> +            'name': sequence.next_by_id(),
@mpanarin at this stage, the move is not confirmed so we need to put name = '/' or even leave empty (and use the default which happens to be '/'

Then the code in the method post() will then get the proper sequence.

2017-12-18 16:10 UTC, mpanarin commented
@gurneyalex fixed

2018-01-31 11:45 UTC, fclementic2c commented
:+1: 
Mergeable ?

2018-02-01 07:26 UTC, gurneyalex commented
@mpanarin there are some LINT errors => red CI. 

@fclementic2c this is a PR on an acsone branch, I can't merge this.

2018-02-01 08:49 UTC, sbidoul commented
I think this naming of journal entries has always been like this (in v8).

I kind of remember customers complaining about this too. @adrienpeiffer @benwillig what was the conclusion? Can we change? Should this be optional?

2018-02-12 08:24 UTC, gurneyalex commented
@sbidoul at least in France, having move names which are not sequential is a sure way to get busted by your finantial auditors / the administration. :-)

2018-10-23 15:59 UTC, gurneyalex requested changes
Please improve commit message: this is not an "IMP" it's a "FIX". Then explain that the previous code is generating account moves with the same number which is a really bad idea.

2018-10-24 12:04 UTC, sbidoul commented
@gurneyalex not we are not going to maintain this branch as it is superseded by the refactoring in https://github.com/OCA/account-financial-tools/pull/677

2018-11-12 08:45 UTC, gurneyalex commented
Hello @sbidoul do you know if there is an easy migration path between this branch and OCA#677 ?

2018-11-12 09:05 UTC, sbidoul commented
@gurneyalex `-u` seems to be sufficient, according to Luc and our own tests.

2019-03-03 10:18 UTC, sbidoul commented
I guess we can close this one.

2019-03-03 10:18 UTC, closed without merging